export const collectionDefinitions = {
  planItems: {
    table: "plan_items",
    title: "title",
    module: "today",
    required: ["title", "plan_date"],
    fields: ["title", "plan_date", "start_time", "estimated_minutes", "priority", "status", "source_module", "source_entity_type", "source_entity_id", "complete_source", "notes", "completed_at"],
    search: ["title", "notes"],
  },
  quickMemos: {
    table: "quick_memos",
    title: "content",
    module: "dashboard",
    required: ["content"],
    fields: ["content", "archived_at", "converted_type", "converted_id"],
    search: ["content"],
  },
  mediaContents: {
    table: "media_contents",
    title: "title",
    module: "media",
    required: ["title"],
    fields: ["title", "platform", "content_format", "stage", "planned_publish_at", "published_at", "copy_text", "asset_path", "publish_url", "views", "likes", "comments", "archived_at"],
    search: ["title", "platform", "copy_text"],
  },
  devProjects: {
    table: "dev_projects",
    title: "name",
    module: "development",
    required: ["name"],
    fields: ["name", "description", "status", "local_path", "repository_url", "document_url", "archived_at"],
    search: ["name", "description"],
  },
  devMilestones: {
    table: "dev_milestones",
    title: "name",
    module: "development",
    required: ["project_id", "name"],
    fields: ["project_id", "name", "target_date", "status"],
    search: ["name"],
  },
  devWorkItems: {
    table: "dev_work_items",
    title: "title",
    module: "development",
    required: ["project_id", "title"],
    fields: ["project_id", "milestone_id", "title", "item_type", "priority", "status", "description"],
    search: ["title", "description"],
  },
  devLogs: {
    table: "dev_logs",
    title: "content",
    module: "development",
    required: ["project_id", "log_date", "content"],
    fields: ["project_id", "log_date", "content"],
    search: ["content"],
  },
  clients: {
    table: "clients",
    title: "name",
    module: "consulting",
    required: ["name"],
    fields: ["name", "notes", "archived_at"],
    search: ["name", "notes"],
  },
  consultingProjects: {
    table: "consulting_projects",
    title: "name",
    module: "consulting",
    required: ["client_id", "name"],
    fields: ["client_id", "name", "current_need", "status", "archived_at"],
    search: ["name", "current_need"],
  },
  consultingInteractions: {
    table: "consulting_interactions",
    title: "notes",
    module: "consulting",
    required: ["project_id", "occurred_at"],
    fields: ["project_id", "occurred_at", "interaction_type", "notes"],
    search: ["notes"],
  },
  consultingDeliverables: {
    table: "consulting_deliverables",
    title: "name",
    module: "consulting",
    required: ["project_id", "name"],
    fields: ["project_id", "name", "due_date", "status"],
    search: ["name"],
  },
  consultingFollowups: {
    table: "consulting_followups",
    title: "content",
    module: "consulting",
    required: ["project_id", "followup_at", "content"],
    fields: ["project_id", "followup_at", "content", "status", "completed_at"],
    search: ["content"],
  },
  consultingTimeEntries: {
    table: "consulting_time_entries",
    title: "notes",
    module: "consulting",
    required: ["project_id", "entry_date"],
    fields: ["project_id", "entry_date", "minutes", "fee_cents", "settled", "notes"],
    search: ["notes"],
  },
  workoutTemplates: {
    table: "workout_templates",
    title: "name",
    module: "fitness",
    required: ["name"],
    fields: ["name", "body_part", "weekday", "notes"],
    search: ["name", "notes"],
  },
  workoutTemplateExercises: {
    table: "workout_template_exercises",
    title: "name",
    module: "fitness",
    required: ["template_id", "name"],
    fields: ["template_id", "name", "target_sets", "target_reps", "target_weight", "rest_seconds", "sort_order"],
    search: ["name"],
  },
  workouts: {
    table: "workouts",
    title: "name",
    module: "fitness",
    required: ["name", "workout_date"],
    fields: ["template_id", "name", "body_part", "workout_date", "status", "feeling", "started_at", "completed_at"],
    search: ["name", "feeling"],
  },
  workoutExercises: {
    table: "workout_exercises",
    title: "name",
    module: "fitness",
    required: ["workout_id", "name"],
    fields: ["workout_id", "name", "sort_order"],
    search: ["name"],
  },
  workoutSets: {
    table: "workout_sets",
    title: "set_number",
    module: "fitness",
    required: ["workout_exercise_id", "set_number"],
    fields: ["workout_exercise_id", "set_number", "reps", "weight", "completed"],
    search: [],
  },
  bodyMetrics: {
    table: "body_metrics",
    title: "metric_date",
    module: "fitness",
    required: ["metric_date"],
    fields: ["metric_date", "weight", "waist", "chest", "body_fat", "notes"],
    search: ["notes"],
  },
  nutritionTargets: {
    table: "nutrition_targets",
    title: "effective_date",
    module: "diet",
    required: ["effective_date"],
    fields: ["effective_date", "calories", "protein", "carbs", "fat"],
    search: [],
  },
  foods: {
    table: "foods",
    title: "name",
    module: "diet",
    required: ["name"],
    fields: ["name", "default_portion", "portion_unit", "calories", "protein", "carbs", "fat"],
    search: ["name"],
  },
  meals: {
    table: "meals",
    title: "name",
    module: "diet",
    required: ["meal_date", "meal_type", "name"],
    fields: ["meal_date", "meal_type", "name", "entry_kind", "notes"],
    search: ["name", "notes"],
  },
  mealItems: {
    table: "meal_items",
    title: "food_name",
    module: "diet",
    required: ["meal_id", "food_name"],
    fields: ["meal_id", "food_id", "food_name", "quantity", "calories", "protein", "carbs", "fat"],
    search: ["food_name"],
  },
  entertainmentItems: {
    table: "entertainment_items",
    title: "name",
    module: "entertainment",
    required: ["name"],
    fields: ["name", "platform", "activity_type", "status", "progress", "next_goal", "notes", "rating", "completed_date"],
    search: ["name", "platform", "progress", "next_goal", "notes"],
  },
  playSessions: {
    table: "play_sessions",
    title: "started_at",
    module: "entertainment",
    required: ["entertainment_id", "started_at"],
    fields: ["entertainment_id", "started_at", "ended_at", "duration_minutes", "progress_note"],
    search: ["progress_note"],
  },
} as const;

export type CollectionName = keyof typeof collectionDefinitions;

export function isCollectionName(value: string): value is CollectionName {
  return Object.hasOwn(collectionDefinitions, value);
}

export const sourceCollectionByType: Record<string, CollectionName> = {
  media_content: "mediaContents",
  dev_work_item: "devWorkItems",
  consulting_deliverable: "consultingDeliverables",
  consulting_followup: "consultingFollowups",
  workout: "workouts",
  meal: "meals",
  entertainment_item: "entertainmentItems",
};
